server:
  port: 8081

springdoc:
  api-docs:
    path: /api-docs

product-catalog:
    url: http://localhost:8082/product-mgmt

product-order:
    url: http://localhost:8080/product-order


logging:
  level:
    web: 'DEBUG'
